name: ESLint

on:
  push:
    branches:
      - main
    paths:
      - client/**

  pull_request:
    branches:
      - main
    paths:
      - client/**

env:
  NODE_VERSION: 16
  WORKING_DIR: client

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIR}}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
