name: Publish to NPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publishing:
    name: Publishing Package to npmjs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
