name: Publish to NPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16
  WORKING_DIR: client
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  publishing:
    name: Publishing Package to npmjs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIR}}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache-dependency-path: ${{env.WORKING_DIR}}/package-lock.json
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create .npmrc
        run: |
          cat << EOF > .npmrc
            //registry.npmjs.org/:_authToken=${{env.NPM_TOKEN}}
            registry=https://registry.npmjs.org/
            always-auth=true
          EOF

      - name: Publish to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{env.NPM_TOKEN}}
          NPM_CONFIG_USERCONFIG: .npmrc
