name: Publish to NPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16
  WORKING_DIR: client
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  linting:
    name: Publishing Package to npmjs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIR}}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache-dependency-path: ${{env.WORKING_DIR}}/package-lock.json
          registry-url: https://registry.npmjs.org/
          always-auth: true
        env:
          NPM_CONFIG_USERCONFIG: ${{env.WORKING_DIR}}/.npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publishing to npmjs
        run: npm publish
        env:
          NPM_CONFIG_USERCONFIG: ${{env.WORKING_DIR}}/.npmrc
