name: Publish to NPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16
  WORKING_DIR: client
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  publishing:
    name: Publishing Package to npmjs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIR}}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: "https://registry.npmjs.org"

      - name: Copy .npmrc to working directory
        run: |
          cp ${{env.GITHUB_WORKSPACE}}/.npmrc ${{env.GITHUB_WORKSPACE}}/${{env.WORKING_DIR}}/.npmrc
          cat ${{env.GITHUB_WORKSPACE}}/${{env.WORKING_DIR}}/.npmrc
          echo "${{env.GITHUB_WORKSPACE}}/${{env.WORKING_DIR}}/.npmrc" >> $NPM_CONFIG_USERCONFIG

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{env.NPM_TOKEN}}
