name: Publish to NPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16
  WORKING_DIR: client

jobs:
  publishing:
    name: Publishing Package to npmjs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIR}}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: NPM login
        run: |
          npm install -g npm-cli-login
          npm-cli-login
        env:
          NPM_USER: ${{secrets.NPM_USER}}
          NPM_PASS: ${{secrets.NPM_PASS}}
          NPM_EMAIL: ${{secrets.NPM_EMAIL}}

      - name: Publish to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: NPM logout
        run: npm logout
