name: Prettier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16
  WORKING_DIR: client

jobs:
  checking-formatting:
    name: Checking formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIR}}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install Dependencies
        run: npm ci

      - name: Code Checking formatting
        run: npm run formatCheck
